export const ADD_TODO_ACTION = 'todoList/addTodo'
export const TOGGLE_TODO_STATUS = 'todoList/toggleTodoStatus'
export const SEARCH_FILTER_CHANGE = 'filters/searchFilterChange'
export const STATUS_FILTER_CHANGE = 'filters/statusFilterChange'
export const STATUS_PRIORITIES_CHANGE = 'filters/prioritiesFilterChange'
